### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by paolorevillosa** [leandro-hermes/action-upload-file#1]
Im trying to use this to upload my file to a website, but workflow job stops because of "repository not found" error

here is my job logs
`Failed to resolve action download info. Error: Unable to resolve action `actions/action-upload-file@v1`, repository not found
Retrying in 18.944 seconds
Failed to resolve action download info. Error: Unable to resolve action `actions/action-upload-file@v1`, repository not found
Retrying in 23.199 seconds
Error: Failed to resolve action download info.`

![repo not found](https://user-images.githubusercontent.com/29852199/105035529-16db5800-5a96-11eb-9070-4cf9001130b9.png)

**Comment by leandro-hermes** [comment]
Tag `v1` in fact does not exists. You must use `actions/action-upload-file@v1.0.2`. I'll update the instructions.

**Comment by paolorevillosa** [comment]
Thanks for the quick response to the issue, but it give me same error, here is my screenshot

![image](https://user-images.githubusercontent.com/29852199/105119266-f0a3cf80-5b0a-11eb-9f12-524504a1b565.png)

**Comment by leandro-hermes** [comment]
Sorry @paolorevillosa, another docs fault. The correct usage is `leandro-hermes/actions-upload-file@v1.0.2`. Already fixed on readme.
